package com.realtimetilegame.game.domain.rule.model;

public enum RuleErrorCode {
    TILE_NOT_FOUND,
    TILE_NOT_OWNED,
    DUPLICATED_TILE,
    MISSING_TILE,

    INVALID_RUN,
    INVALID_GROUP,
    INVALID_MELD,
    INVALID_TABLE_LAYOUT,

    INITIAL_MELD_SCORE_TOO_LOW,
    TABLE_MANIPULATION_NOT_ALLOWED_ON_INITIAL_MELD,

    NO_RACK_TILE_USED,

    INVALID_JOKER_REPLACEMENT,
    RETRIEVED_JOKER_NOT_REUSED,
    JOKER_RETRIEVAL_NOT_ALLOWED
}
