apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: realtime-tile-game
  labels:
    app.kubernetes.io/name: realtime-tile-game
    app.kubernetes.io/part-of: realtime-tile-game
    app.kubernetes.io/component: mysql
    app.kubernetes.io/managed-by: kubectl
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: realtime-tile-game
    app.kubernetes.io/component: mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
      protocol: TCP
