apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: realtime-tile-game
  labels:
    app.kubernetes.io/name: realtime-tile-game
    app.kubernetes.io/part-of: realtime-tile-game
    app.kubernetes.io/component: frontend
    app.kubernetes.io/managed-by: kubectl
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: realtime-tile-game
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 30517
      protocol: TCP
